name: Hub
version: '${project.version}'
main: com.valoriom
api-version: 1.18
authors: Valoriom
description: Simple HubCore made for all.
depends:
 - Core

commands:
  setspawn:
    description: set spawn command
  spawn:
    description: spawn command
